### PR TITLE
StaticArrays@v1 & Travis -> GitHub Actions

### PR DESCRIPTION
**Pull request by lmh91**

### CODE REVIEW

**Comment by lmh91** [comment]
Maybe also a new release after this one? @oschulz

**Comment by lmh91** [comment]
PR #15 can be closed due to this PR.

**Comment by oschulz** [comment]
Thanks! Could you also replace TagBot.yml and CompatHelper.yml with the version in JuliaPackageTemplate.jl?

**Comment by lmh91** [comment]
Done

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
